# External Secrets Operator - ClusterSecretStore for MTN Admission System
# Centralized secret management with Vault integration
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: mtn-vault-backend
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: cluster-secret-store
    app.kubernetes.io/part-of: mtn-admission
spec:
  provider:
    vault:
      # Vault server configuration
      server: "https://vault.mtn.cl"
      path: "kv"
      version: "v2"
      namespace: "mtn-admission"
      
      # Authentication using Kubernetes service account
      auth:
        kubernetes:
          # Path where Kubernetes auth method is mounted
          mountPath: "kubernetes"
          # Role for MTN admission system
          role: "mtn-admission-external-secrets"
          # Service account token for authentication
          serviceAccountRef:
            name: "external-secrets-operator"
            namespace: "external-secrets-system"
          
      # TLS configuration for secure communication
      tls:
        # Custom CA certificate for Vault
        caBundle: |
          LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
          MIIDOzCCAiOgAwIBAgIJAK4G1OvYu3ANMA0GCSqGSIb3DQEBCwUAMDQxCzAJBgNV
          BAYTAkNMMQ0wCwYDVQQIDARNVE4xDTALBgNVBAcMBE10TjELMAkGA1UECgwCTU4w
          HhcNMjQwMTAxMDAwMDAwWhcNMjkwMTAxMDAwMDAwWjA0MQswCQYDVQQGEwJDTDEN
          MAsGA1UECAwETVROMQ0wCwYDVQQHDARNdE4xCzAJBgNVBAoMAk1OMIIBIjANBgkq
          hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4f6wX8dWqvQJ5nF1gHZn7sJlKuY2wqHy
          LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
        
        # Server name for TLS verification
        serverName: "vault.mtn.cl"
        
        # Minimum TLS version for Chilean compliance
        minVersion: "1.2"
        
        # Allowed cipher suites
        cipherSuites:
          - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
          - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
          - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
          - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
      
      # Connection timeout and retry configuration
      timeout: "30s"
      readTimeout: "30s"
      
      # Headers for Chilean compliance
      headers:
        X-Vault-Request-Origin: "mtn-admission-k8s"
        X-Vault-Client-Type: "external-secrets-operator"

  # Retry configuration for resilience
  retrySettings:
    maxRetries: 5
    retryInterval: "10s"

  # Rate limiting to avoid overwhelming Vault
  rateLimiter:
    requests: 100
    period: "60s"

---
# SecretStore for admissions namespace
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: mtn-vault-admission
  namespace: admissions
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: secret-store
    app.kubernetes.io/part-of: mtn-admission
spec:
  provider:
    vault:
      server: "https://vault.mtn.cl"
      path: "kv"
      version: "v2"
      namespace: "mtn-admission"
      
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "mtn-admission-services"
          serviceAccountRef:
            name: "vault-auth"
            namespace: "admissions"
      
      tls:
        caBundle: |
          LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
          MIIDOzCCAiOgAwIBAgIJAK4G1OvYu3ANMA0GCSqGSIb3DQEBCwUAMDQxCzAJBgNV
          BAYTAkNMMQ0wCwYDVQQIDARNVE4xDTALBgNVBAcMBE10TjELMAkGA1UECgwCTU4w
          HhcNMjQwMTAxMDAwMDAwWhcNMjkwMTAxMDAwMDAwWjA0MQswCQYDVQQGEwJDTDEN
          MAsGA1UECAwETVROMQ0wCwYDVQQHDARNdE4xCzAJBgNVBAoMAk1OMIIBIjANBgkq
          hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4f6wX8dWqvQJ5nF1gHZn7sJlKuY2wqHy
          LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
        serverName: "vault.mtn.cl"
        minVersion: "1.2"

---
# SecretStore for infrastructure namespace (databases, message queues)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: mtn-vault-infrastructure
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: secret-store
    app.kubernetes.io/part-of: mtn-admission
spec:
  provider:
    vault:
      server: "https://vault.mtn.cl"
      path: "database"
      version: "v1"
      namespace: "mtn-admission"
      
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "mtn-admission-infrastructure"
          serviceAccountRef:
            name: "vault-auth"
            namespace: "infrastructure"
      
      tls:
        caBundle: |
          LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
          MIIDOzCCAiOgAwIBAgIJAK4G1OvYu3ANMA0GCSqGSIb3DQEBCwUAMDQxCzAJBgNV
          BAYTAkNMMQ0wCwYDVQQIDARNVE4xDTALBgNVBAcMBE10TjELMAkGA1UECgwCTU4w
          HhcNMjQwMTAxMDAwMDAwWhcNMjkwMTAxMDAwMDAwWjA0MQswCQYDVQQGEwJDTDEN
          MAsGA1UECAwETVROMQ0wCwYDVQQHDARNdE4xCzAJBgNVBAoMAk1OMIIBIjANBgkq
          hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4f6wX8dWqvQJ5nF1gHZn7sJlKuY2wqHy
          LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
        serverName: "vault.mtn.cl"
        minVersion: "1.2"