# Loki Configuration for MTN Admission System
# Optimized for Chilean timezone and PII masking

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://alertmanager:9093

# Limits configuration for MTN scale
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h # 1 week
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  max_streams_per_user: 10000
  max_line_size: 256kb
  max_entries_limit_per_query: 10000
  max_global_streams_per_user: 5000
  
  # Retention configuration for Chilean compliance
  retention_period: 180d  # 6 months for audit compliance
  
  # Query limits
  max_query_length: 721h  # ~30 days
  max_query_parallelism: 32
  max_concurrent_tail_requests: 10
  
  # Cardinality control
  max_label_name_length: 1024
  max_label_value_length: 4096
  max_label_names_per_series: 30

# Table manager for retention
table_manager:
  retention_deletes_enabled: true
  retention_period: 180d

# Storage configuration
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

chunk_store_config:
  max_look_back_period: 0s

# Compactor for chunk management
compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem

# Frontend configuration
frontend:
  max_outstanding_per_tenant: 256
  compress_responses: true
  downstream_url: http://127.0.0.1:3100

# Query frontend worker
frontend_worker:
  frontend_address: 127.0.0.1:9095
  parallelism: 10
  match_max_concurrent: true

# Analytics configuration
analytics:
  reporting_enabled: false