server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: admision-mtn
  
  # Configuración de base de datos PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/Admision_MTN_DB
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  
  # Configuración JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql
    defer-datasource-initialization: false
  
  # Configuración de Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:jorge.gangale@mtn.cl}
    password: ${MAIL_PASSWORD:aepg xtjo kunu nvwn}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  
  # DevTools
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  
  # Configuración multipart
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

# Configuración CORS
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://localhost:5173
    - http://localhost:5174
    - http://localhost:5175
    - http://localhost:5176
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true

# Configuración JWT
jwt:
  secret: ${JWT_SECRET:myVerySecureJWTSecretKey1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789SECURE_KEY_FOR_HS512_ALGORITHM_MINIMUM_512_BITS_REQUIRED}
  expiration: 86400000 # 24 horas en milisegundos

# Configuración de archivos
app:
  upload:
    dir: uploads
    max-file-size: 10MB
    max-request-size: 10MB

# Configuración de logging
logging:
  level:
    com.desafios.admision_mtn: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/admision-mtn.log