server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/}

spring:
  application:
    name: admision-mtn
  
  # Configuración de base de datos PostgreSQL - USAR VARIABLES DE ENTORNO
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:Admisión_MTN_DB}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin123}
    driver-class-name: org.postgresql.Driver
  
  # Configuración JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        # Forzar regeneración de metadatos y deshabilitar cache
        cache:
          use_second_level_cache: false
          use_query_cache: false
        order_updates: true
        order_inserts: true
        connection:
          autocommit: false
    database: postgresql
    defer-datasource-initialization: false
  
  # Configuración de Mail Institucional - USAR VARIABLES DE ENTORNO
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:admision@mtn.cl}
    password: ${SMTP_PASSWORD:your_institutional_app_password_here}
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH:true}
          starttls:
            enable: ${SMTP_STARTTLS:true}
          ssl:
            trust: ${SMTP_HOST:smtp.gmail.com}
          # Configuración adicional para volumen institucional
          connectiontimeout: 30000
          timeout: 30000
          writetimeout: 30000
    # Configuración de protocolo mejorada para institucional
    default-encoding: UTF-8
    protocol: smtp
  
  # DevTools
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  
  # Configuración multipart
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:50MB}
      enabled: true

# Configuración CORS
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://localhost:5173
    - http://localhost:5174
    - http://localhost:5175
    - http://localhost:5176
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true

# Configuración JWT - CAMBIAR SECRET EN PRODUCCIÓN
jwt:
  secret: ${JWT_SECRET:myVerySecureJWTSecretKey1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789SECURE_KEY_FOR_HS512_ALGORITHM_MINIMUM_512_BITS_REQUIRED}
  expiration: ${JWT_EXPIRATION_TIME:86400000} # 24 horas en milisegundos

# Configuración de archivos
app:
  upload:
    dir: ${UPLOAD_PATH:uploads}
    max-file-size: ${MAX_FILE_SIZE:10MB}
    max-request-size: ${MAX_REQUEST_SIZE:50MB}
  # Configuración institucional de emails
  institutional-email:
    from-name: ${INSTITUTIONAL_EMAIL_FROM_NAME:Colegio Monte Tabor y Nazaret - Sistema de Admisión}
    reply-to: ${INSTITUTIONAL_EMAIL_REPLY_TO:admision@mtn.cl}
    support-email: ${INSTITUTIONAL_EMAIL_SUPPORT:soporte@mtn.cl}
    website: ${INSTITUTIONAL_WEBSITE:www.mtn.cl}
    phone: ${INSTITUTIONAL_PHONE:+56 2 2234 5678}
    # Límites y control de volumen
    max-emails-per-hour: ${MAX_EMAILS_PER_HOUR:50}
    max-emails-per-day: ${MAX_EMAILS_PER_DAY:200}
    max-emails-per-month: ${MAX_EMAILS_PER_MONTH:5000}
    # Rate limiting y retry
    retry-attempts: ${EMAIL_RETRY_ATTEMPTS:4}
    retry-delay-minutes: ${EMAIL_RETRY_DELAY_MINUTES:5}
    queue-max-size: ${EMAIL_QUEUE_MAX_SIZE:100}
  # Base URL para tracking y respuestas
  base-url: ${APP_BASE_URL:http://localhost:8080}

# Configuración de logging
logging:
  level:
    com.desafios.admision_mtn: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/admision-mtn.log