{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "<service>.fullname" . }}
  labels:
    {{- include "<service>.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- with .Values.configMap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  
  # Service metadata
  SERVICE_NAME: {{ include "<service>.name" . }}
  SERVICE_VERSION: {{ .Values.image.tag | default .Chart.AppVersion }}
  BUILD_SHA: {{ .Values.build.sha | default "unknown" }}
  BUILD_URL: {{ .Values.build.url | default "unknown" }}
  DEPLOYMENT_ID: {{ .Values.build.deploymentId | default "unknown" }}
  DEPLOYMENT_TIMESTAMP: {{ .Values.build.timestamp | default (now | date "2006-01-02T15:04:05Z07:00") }}
  TRIGGERED_BY: {{ .Values.build.triggeredBy | default "unknown" }}
  
  # Kubernetes metadata
  NAMESPACE: {{ .Release.Namespace }}
  RELEASE_NAME: {{ .Release.Name }}
  CHART_VERSION: {{ .Chart.Version }}
  APP_VERSION: {{ .Chart.AppVersion }}
  
  # Environment configuration
  ENVIRONMENT: {{ .Values.commonLabels.environment | default "development" }}
  LOG_LEVEL: {{ .Values.env | default list | dict "name" "LOGGING_LEVEL_ROOT" | default "INFO" }}
  
  # Application configuration file
  application.yml: |
    spring:
      application:
        name: {{ include "<service>.name" . }}
      profiles:
        active: kubernetes
      
    server:
      port: {{ .Values.service.targetPort }}
      shutdown: graceful
      
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
          base-path: /actuator
      endpoint:
        health:
          show-details: always
        info:
          show-details: always
        metrics:
          enabled: true
        prometheus:
          enabled: true
      metrics:
        export:
          prometheus:
            enabled: true
        tags:
          application: {{ include "<service>.name" . }}
          environment: {{ .Values.commonLabels.environment | default "development" }}
          version: {{ .Values.image.tag | default .Chart.AppVersion }}
      
    logging:
      level:
        com.desafios.mtn: {{ .Values.env | default list | dict "name" "LOGGING_LEVEL_COM_DESAFIOS_MTN" | default "INFO" }}
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
      file:
        name: /app/logs/{{ include "<service>.name" . }}.log
        
    # Observability
    tracing:
      enabled: {{ .Values.configMap.data.TRACING_ENABLED | default "true" }}
      jaeger:
        endpoint: {{ .Values.configMap.data.JAEGER_ENDPOINT | default "http://jaeger-collector.monitoring.svc.cluster.local:14268/api/traces" }}
{{- end }}