{{- if .Values.monitoring.enabled }}
{{- if .Values.monitoring.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "<service>.fullname" . }}
  {{- if .Values.monitoring.serviceMonitor.namespace }}
  namespace: {{ .Values.monitoring.serviceMonitor.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "<service>.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.monitoring.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "<service>.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    {{- if .Values.monitoring.serviceMonitor.path }}
    path: {{ .Values.monitoring.serviceMonitor.path }}
    {{- end }}
    {{- if .Values.monitoring.serviceMonitor.interval }}
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.monitoring.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
    {{- end }}
    {{- if .Values.monitoring.serviceMonitor.honorLabels }}
    honorLabels: {{ .Values.monitoring.serviceMonitor.honorLabels }}
    {{- end }}
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'http_server_requests_total'
      targetLabel: __name__
      replacement: 'mtn_http_requests_total'
    - sourceLabels: [__name__]
      regex: 'http_server_requests_seconds.*'
      targetLabel: __name__
      replacement: 'mtn_http_request_duration_${1}'
    - sourceLabels: [application]
      targetLabel: service
      replacement: {{ include "<service>.name" . }}
    - sourceLabels: [instance]
      targetLabel: pod
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: kubernetes_namespace
    - sourceLabels: [__meta_kubernetes_service_name]
      targetLabel: kubernetes_service_name
{{- end }}

{{- if .Values.monitoring.prometheusRule.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "<service>.fullname" . }}
  {{- if .Values.monitoring.prometheusRule.namespace }}
  namespace: {{ .Values.monitoring.prometheusRule.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "<service>.labels" . | nindent 4 }}
    {{- with .Values.monitoring.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.monitoring.prometheusRule.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  groups:
  - name: {{ include "<service>.name" . }}.rules
    interval: 30s
    rules:
    {{- with .Values.monitoring.prometheusRule.rules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    
    # Additional standard rules for microservice monitoring
    - alert: {{ include "<service>.name" . | title }}PodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total{pod=~"{{ include "<service>.fullname" . }}-.*"}[15m]) > 0
      for: 5m
      labels:
        severity: warning
        service: {{ include "<service>.name" . }}
        environment: {{ .Values.commonLabels.environment | default "unknown" }}
      annotations:
        summary: "Pod is crash looping"
        description: "Pod {{ `{{ $labels.pod }}` }} is restarting frequently"
        runbook_url: "https://runbooks.mtn.cl/{{ include "<service>.name" . }}/pod-crash-looping"

    - alert: {{ include "<service>.name" . | title }}PodNotReady
      expr: kube_pod_status_ready{condition="false", pod=~"{{ include "<service>.fullname" . }}-.*"} == 1
      for: 5m
      labels:
        severity: warning
        service: {{ include "<service>.name" . }}
        environment: {{ .Values.commonLabels.environment | default "unknown" }}
      annotations:
        summary: "Pod not ready"
        description: "Pod {{ `{{ $labels.pod }}` }} has been not ready for more than 5 minutes"
        runbook_url: "https://runbooks.mtn.cl/{{ include "<service>.name" . }}/pod-not-ready"

    - alert: {{ include "<service>.name" . | title }}DeploymentReplicasMismatch
      expr: |
        kube_deployment_status_replicas{deployment="{{ include "<service>.fullname" . }}"} !=
        kube_deployment_status_replicas_available{deployment="{{ include "<service>.fullname" . }}"}
      for: 10m
      labels:
        severity: warning
        service: {{ include "<service>.name" . }}
        environment: {{ .Values.commonLabels.environment | default "unknown" }}
      annotations:
        summary: "Deployment replica mismatch"
        description: "Deployment {{ `{{ $labels.deployment }}` }} has mismatched replicas for 10+ minutes"
        runbook_url: "https://runbooks.mtn.cl/{{ include "<service>.name" . }}/replica-mismatch"

    - alert: {{ include "<service>.name" . | title }}HighJVMHeapUsage
      expr: |
        (jvm_memory_used_bytes{job="{{ include "<service>.name" . }}", area="heap"} /
         jvm_memory_max_bytes{job="{{ include "<service>.name" . }}", area="heap"}) > 0.9
      for: 5m
      labels:
        severity: warning
        service: {{ include "<service>.name" . }}
        environment: {{ .Values.commonLabels.environment | default "unknown" }}
      annotations:
        summary: "High JVM heap usage"
        description: "JVM heap usage is {{ `{{ $value | humanizePercentage }}` }}"
        runbook_url: "https://runbooks.mtn.cl/{{ include "<service>.name" . }}/high-jvm-heap"

    - alert: {{ include "<service>.name" . | title }}DatabaseConnectionsExhausted
      expr: |
        (hikaricp_connections_active{job="{{ include "<service>.name" . }}"} /
         hikaricp_connections_max{job="{{ include "<service>.name" . }}"}) > 0.9
      for: 2m
      labels:
        severity: critical
        service: {{ include "<service>.name" . }}
        environment: {{ .Values.commonLabels.environment | default "unknown" }}
      annotations:
        summary: "Database connections nearly exhausted"
        description: "Database connection pool is {{ `{{ $value | humanizePercentage }}` }} full"
        runbook_url: "https://runbooks.mtn.cl/{{ include "<service>.name" . }}/db-connections-exhausted"

    - alert: {{ include "<service>.name" . | title }}SlowDatabaseQueries
      expr: |
        histogram_quantile(0.99,
          sum by (le) (rate(hikaricp_connections_usage_seconds_bucket{job="{{ include "<service>.name" . }}"}[5m]))
        ) > 1
      for: 5m
      labels:
        severity: warning
        service: {{ include "<service>.name" . }}
        environment: {{ .Values.commonLabels.environment | default "unknown" }}
      annotations:
        summary: "Slow database queries detected"
        description: "99th percentile query time is {{ `{{ $value }}` }} seconds"
        runbook_url: "https://runbooks.mtn.cl/{{ include "<service>.name" . }}/slow-queries"
{{- end }}
{{- end }}